module.exports = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LYRICRECEIEVED: "LYRICRECEIEVED",
  RESULTSRECIEVED: "RESULTSRECIEVED",
  LYRICSRECEIEVED: "LYRICSRECEIEVED",
  SETERRORS: "SETERRORS",
  CLEARERRORS: "CLEARERRORS"
};
